version: '3.9'

services:
  db:
    image: "postgres:16.0"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: nila
      POSTGRES_PASSWORD: nilasoft
      POSTGRES_DB: nila_soft_blog
  redis:
    image: redis:latest
    ports:
      - "6379:6379"