spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/nila_soft_blog
    username: nila
    password: nilasoft
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    locations: classpath:db.migration
    enabled: true
  main:
    allow-bean-definition-overriding: true
  cache:
    type: redis
    cache-names:
      - user
      - post
      - comment
    redis:
      time-to-live: 600000
      cache-null-values: true
  data:
    redis:
      host: localhost
      port: 6379
