spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blog_service
    username: postgres
    password: ali.1381
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    locations: classpath:db.migration
